### ISSUE TITLE
layoutSubviews会执行两次

### ISSUE THREAD

**Issue by BaanX** [LBCoderLee/iOS_XianYu#2]
加入中间btn设置为不规则图形的话, layoutSubviews执行两次,导致出现两个标题.

**Comment by LBCoderLee** [comment]
那这样就有点坑了，谢谢你发现了这个问题，我看看哈

**Comment by BaanX** [comment]
好的 如果有结果 拜托给个回复哈! 因为我也没搞明白 该怎么解决...

**Comment by leewaycn** [comment]
虽然执行了2次，但透视它的结构，没发现2个标题哦。

**Comment by BaanX** [comment]
你原本竖屏，再横屏试试 中间就会出现两个

**Comment by leewaycn** [comment]
果然是。要把这个label 放在init里。layoutsubview 时只改变坐标

**Comment by BaanX** [comment]
是 我也是今天解决的 给放到init里面了 刚想告诉你下
